require("user.options")
require("user.notify")
require("user.dressing")

require("user.autocommands")

require("user.treesitter")
require("user.dap")
require("user.lsp")

require("user.telescope")
require("user.autopairs")
require("user.bufferline")
require("user.cmp")
require("user.colorizer")
require("user.colors")
require("user.impatient")
require("user.keymaps")
require("user.lualine")
require("user.ntree")
require("user.plugins")
require("user.tabnine")
require("user.gitsigns")
require("user.norg")
require("user.comment")
require("user.fidget")

require("user.alpha")
--require("user.copilot")
require("user.crates")
require("user.illuminate")
require("user.neoscroll")
require("user.renamer")
require("user.todo_comments")
require("user.web_icons")
require("user.whichkey")

require("user.code_actions_menu")
require("user.flutter")
require("user.project")
