require("user.options")
require("user.notify")

require("user.autocommands")

require("user.treesitter")
require("user.dap")
require("user.lsp")

require("user.telescope")
require("user.autopairs")
require("user.bufferline")
require("user.cmp")
require("user.colorizer")
require("user.colors")
require("user.impatient")
require("user.keymaps")
require("user.lualine")
require("user.ntree")
require("user.plugins")
require("user.tabnine")
require("user.gitsigns")
require("user.norg")
require("user.comment")
require("user.fidget")
--TODO: onehalf colors termilal setup
